### ISSUE TITLE
Menyusun Proposal

### ISSUE THREAD

**Issue by arikurniawans** [kampusubl/smart-hidroponik#2]

**Comment by Marzuki001** [comment]
proposal sudah disubmit

**Comment by agussukoco** [comment]
ari, minta tolong ya, untuk dimasukkan ke form usulan
[Perencanaan Topik Penelitian v.01.docx](https://github.com/kampusubl/smart-hidroponik/files/451529/Perencanaan.Topik.Penelitian.v.01.docx)
[TOPIK.docx](https://github.com/kampusubl/smart-hidroponik/files/451530/TOPIK.docx)
[TOPIK_Traffic Revolution v.00.docx](https://github.com/kampusubl/smart-hidroponik/files/451531/TOPIK_Traffic.Revolution.v.00.docx)
